In [1]:
import math
math.sqrt(25)

5.0

In [10]:
from math import sqrt
sqrt(36)

6.0

In [11]:
from math import cos, floor
floor(3.6)

3

In [12]:
cos(0)

1.0

In [ ]:
import numpy as np

In [13]:
2 ** 2

4

In [14]:
10 / 4

2.5

In [15]:
10 // 4

2

In [16]:
5 % 4

1

In [17]:
5 == 3

False

In [18]:
5 > 3 and 2 < 4

True

In [21]:
type('2')

str

In [22]:
isinstance(2, int)

True

In [23]:
int(2.3)

2

In [24]:
empty_list = []
empty_list = list()

In [25]:
a = ['million', 'ai', 'class']

In [26]:
a[0]

'million'

In [27]:
mix = [2, 'million', 3.5]

In [28]:
len(mix)

3

In [51]:
g = [1, 2, 3]

In [52]:
h = [4, 5, 6]

In [53]:
g.append(h)

In [54]:
g

[1, 2, 3, [4, 5, 6]]

In [55]:
z = [4, 5, 6]
y = [1, 2, 3]
z.extend(y)
z

[4, 5, 6, 1, 2, 3]

In [58]:
weekdays = ['mon', 'tue', 'wed', 'thur', 'fri']
print(weekdays[0])
print(weekdays[-1])

mon
fri


In [59]:
weekdays[0:3]

['mon', 'tue', 'wed']

In [60]:
weekdays[::2]

['mon', 'wed', 'fri']

In [61]:
weekdays[::-1]

['fri', 'thur', 'wed', 'tue', 'mon']

In [62]:
sorted(weekdays)

['fri', 'mon', 'thur', 'tue', 'wed']

In [63]:
weekdays

['mon', 'tue', 'wed', 'thur', 'fri']

In [71]:
weekdays[-3:]

['wed', 'thur', 'fri']

In [74]:
# this is a comment
weekdays.sort(reverse=True)

In [75]:
weekdays

['wed', 'tue', 'thur', 'mon', 'fri']

In [76]:
newlist = [1, 2, 3] + ['a', 'b', 'c']

In [77]:
newlist

[1, 2, 3, 'a', 'b', 'c']

In [79]:
['a'] * 3

['a', 'a', 'a']

In [80]:
# tuple
digits = (0, 1, 'two')

In [81]:
digits

(0, 1, 'two')

In [82]:
digits = tuple([1, 1, 2, 3, 'a'])

In [83]:
digits

(1, 1, 2, 3, 'a')

In [87]:
zero = (0,)

In [89]:
zero
type(zero)

tuple

In [ ]:
problem = (3 * 2) - 14

In [90]:
digits.count(1)

2

In [91]:
digits.index(1)

0

In [92]:
digits[2] = 2

TypeError: 'tuple' object does not support item assignment

In [93]:
# String
s = str(42)
s

'42'

In [94]:
s = 'this is python'
s[0]

't'

In [96]:
print(s.split()[1:])

['is', 'python']


In [97]:
s.split()

['this', 'is', 'python']

In [98]:
s.split()[1:]

['is', 'python']

In [102]:
print('\n'.join(s.split()[1:]))

is
python


In [103]:
s

'this is python'

In [104]:
s[3:7]

's is'

In [105]:
s[-1]

'n'

In [107]:
s.upper()

'THIS IS PYTHON'

In [108]:
s.title()

'This Is Python'

In [110]:
s.startswith('t')

True

In [111]:
s.find('is')

2

In [113]:
s1 = 'python'
s2 = 'is easy'

s1 + ' ' + s2

'python is easy'

In [114]:
print(s1 + s2)

pythonis easy


In [118]:
print(f"This is an int %.2f" % 10)

This is an int 10.00


In [119]:
print(f"this is an int {10} - {2**3}")

this is an int 10 - 8


In [120]:
print('raining %s and %s' % ('cats', 'dogs'))

raining cats and dogs


In [124]:
print('raining {} and {}'.format('cats', 'dogs'))

raining cats and dogs


In [125]:
dictionary = {'a': 1, 'b': 2, 'c': 3}

In [126]:
dictionary.keys()

dict_keys(['a', 'b', 'c'])

In [127]:
dictionary.values()

dict_values([1, 2, 3])

In [128]:
dictionary.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [130]:
x = dict(a='value1', b='value2')

In [131]:
x

{'a': 'value1', 'b': 'value2'}

In [132]:
dictionary['b']

2

In [136]:
# Sets
s = [1, 2, 3, 3, 4]
s = set(s)
print(s)

s = {1, 2, 3, 3, 4}
type(s)

{1, 2, 3, 4}


set

In [137]:
languages = {'python', 'r', 'java'}
snakes = set(['cobra', 'viper', 'python'])

In [138]:
languages | snakes

{'cobra', 'java', 'python', 'r', 'viper'}

In [139]:
languages & snakes

{'python'}

In [140]:
languages - snakes

{'java', 'r'}

In [141]:
x = 3
if x > 0:
    print('positive')

positive


In [142]:
if x < 0:
    print('negative')
else:
    print('else statment')

else statment


In [ ]:
if x:
    print()
elif x == 3:
    print()
else:
    print()

In [145]:
if x > 0: print('positive')

positive


In [146]:
# one-liners
sign = 'positive' if x > 0 else 'negative'

In [147]:
sign

'positive'

In [8]:
# for loop
loop_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# for i in range(len(loop_list)):
#     print(loop_list[i]**2)
    
    
# for i in loop_list[::2]:
#     print(i**2)
    
for i in [1, 2, 3, 4, 5]:
    print(i**3)

1
8
27
64
125


In [15]:
new_list = ['a', 'b', 'c']

i = 0
while i < len(new_list):
    print(new_list[i])
    i += 1

print('exit loop')

a
b
c
exit loop


In [21]:
# Count words in a sentence
quote = """
our incomes are like our shoes; if too small they gall and pinch us
but if too large they cause us to stumble and trip
"""

words = quote.split()
count = 0
for i in words:
    count += 1
print(count)

25


In [22]:
print(words)

['our', 'incomes', 'are', 'like', 'our', 'shoes;', 'if', 'too', 'small', 'they', 'gall', 'and', 'pinch', 'us', 'but', 'if', 'too', 'large', 'they', 'cause', 'us', 'to', 'stumble', 'and', 'trip']


In [23]:
dictionary = {}
for word in words:
    if word in dictionary:
        dictionary[word] +=1 
    else:
        dictionary[word] = 1

print(dictionary)

{'our': 2, 'incomes': 1, 'are': 1, 'like': 1, 'shoes;': 1, 'if': 2, 'too': 2, 'small': 1, 'they': 2, 'gall': 1, 'and': 2, 'pinch': 1, 'us': 2, 'but': 1, 'large': 1, 'cause': 1, 'to': 1, 'stumble': 1, 'trip': 1}


In [24]:
count = {k:0 for k in set(quote.split())}
for word in quote.split():
    count[word] += 1
print(count)

{'us': 2, 'they': 2, 'pinch': 1, 'large': 1, 'stumble': 1, 'shoes;': 1, 'gall': 1, 'if': 2, 'cause': 1, 'are': 1, 'our': 2, 'but': 1, 'trip': 1, 'like': 1, 'small': 1, 'incomes': 1, 'to': 1, 'too': 2, 'and': 2}


In [27]:
# iterate through two things at once
family = {'dad':'homer', 'mom':'marge', 'size':6}

for key, value in family.items():
    print(key, value)

dad homer
mom marge
size 6


In [30]:
fruits = ['apple', 'banana', 'orange']

for i, j in enumerate(fruits):
    print(i, j)
    
    (1,)

0 apple
1 banana
2 orange


In [32]:
list1 = [1, 2, 3, 4]
list2 = ['a', 'b', 'c', 'd', 'e']

for i, j in zip(list1, list2):
    print(f"{i}{j}")

1a
2b
3c
4d


In [33]:
# exceptions
dictionary = dict(a=[1, 2], b=[4, 5])

key = 'c'

try:
    dictionary['c']
except:
    print(f"Key {key} is missing")

print(dictionary)

Key c is missing
{'a': [1, 2], 'b': [4, 5]}


In [36]:
# functions: factorial

# recursive approach
def r_factorial(n):
    if n < 2:
        return 1
    else:
        return n * r_factorial(n - 1)
    
# iterative approach
def i_factorial(n):
    if n < 0:
        return "Input is negative"
    
    result = 1
    
    for i in range(1, n+1):
        result *= i
    
    return result
    
print(r_factorial(5))
print(i_factorial(5))

120
120


In [38]:
# List comprehensions

nums = [1, 2, 3, 4, 5]

for i in nums:
    print(i**2, end=" ")

1 4 9 16 25 

In [39]:
print([i**2 for i in nums])

[1, 4, 9, 16, 25]


In [42]:
print("hello", [i for i in nums if i % 2 != 0], "just did")

hello [1, 3, 5] just did


In [44]:
matrix = [[1, 2], [3, 4]]

items = []
for row in matrix:
    for col in row:
        items.append(col)

print(items)

[1, 2, 3, 4]


In [45]:
items = [col for row in matrix for col in row]

print(items)

[1, 2, 3, 4]


In [50]:
simpsons = {'Homer':45, 'Marge':45, 'Bar':10, 'Lisa':10}

for key, value in simpsons.items():
    print(key.upper(), simpsons[key], end="\t")

HOMER 45	MARGE 45	BAR 10	LISA 10	

In [54]:
{k.upper(): v+1 for k, v in simpsons.items()}

In [66]:
# Regular expressions

import re

pattern1 = re.compile("[A-Za-z]+")
pattern2 = re.compile("[^A-Za-z]+")

sentence = "I am a student of CS."

print(pattern1.findall(sentence))
print(pattern2.findall(sentence))

['I', 'am', 'a', 'student', 'of', 'CS']
[' ', ' ', ' ', ' ', ' ', '.']


# Numpy and Pandas

In [1]:
import numpy as np

In [2]:
data1 = [1, 2, 3, 4]
arr1 = np.array(data1)

In [3]:
type(data1)

list

In [4]:
type(arr1)

numpy.ndarray

In [6]:
data2 = [range(1, 5), range(5, 9)]

In [8]:
arr2 = np.array(data2) # 2D array

In [9]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

In [15]:
init_arr = np.arange(5)

In [16]:
init_arr

array([0, 1, 2, 3, 4])

In [18]:
np.arange(2, 5)

array([2, 3, 4])

In [19]:
# Reshaping
arr = np.arange(10, dtype=float)

In [20]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
arr.reshape((2, 5))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [27]:
arr.reshape((5, -1))

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [30]:
# add an axis

# a = np.array([0, 1])
a = np.arange(2)

In [31]:
a

array([0, 1])

In [33]:
a_col = a[:, np.newaxis]

In [34]:
a_col

array([[0],
       [1]])

In [36]:
print(a_col.T)

[[0 1]]


In [37]:
a = np.array([0, 1])

In [38]:
a

array([0, 1])

In [39]:
a.T

array([0, 1])

In [44]:
print(a.T)

[0 1]


In [40]:
b = np.array([[0, 1]])
b

array([[0, 1]])

In [41]:
b.T

array([[0],
       [1]])

In [42]:
a.shape

(2,)

In [45]:
b.shape

(1, 2)

In [46]:
a.T

array([0, 1])

In [47]:
a.shape

(2,)

In [48]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
# Flatten: always returns a flat copy of the orig array
matrix = arr.reshape((5, 2))

In [51]:
matrix

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [52]:
matrix_flat = matrix.flatten()

In [53]:
matrix_flat

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
x = np.arange(2 * 3 * 4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [55]:
x = x.reshape(2, 3, 4)

In [56]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [57]:
# indexing
print(x[0, :, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
print(x[0, 0, 1])

1


In [60]:
# stacking arrays
a = np.array([0, 1])
b = np.array([2, 3])

ab = np.stack((a, b))

In [61]:
ab

array([[0, 1],
       [2, 3]])

In [62]:
abT = np.stack((a, b)).T

In [63]:
abT

array([[0, 2],
       [1, 3]])

In [70]:
# or instead of taking transpose, hstack them
np.hstack((a[:, None], b[:, None]))

array([[0, 2],
       [1, 3]])

In [71]:
abT

array([[0, 2],
       [1, 3]])

In [72]:
abT[0]

array([0, 2])

In [73]:
abT[0][1]

2

In [81]:
abT[:, 1:]

array([[2],
       [3]])

In [82]:
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
arr[::-1]

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.])

In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Will'])

In [87]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [89]:
# Vectorized Operations

nums = np.arange(5)
nums * 10

array([ 0, 10, 20, 30, 40])

In [90]:
nums = np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [91]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [94]:
# compute Euclidean distance
vec1 = np.random.randn(10)
vec2 = np.random.randn(10)

In [95]:
dist = np.sqrt(np.sum((vec1 - vec2) ** 2))

In [96]:
dist

4.855607852089475

In [98]:
rnd = np.random.randn(4, 2)

In [99]:
rnd

array([[-0.03506792, -1.46150884],
       [-1.8528755 , -2.62243169],
       [ 1.07872492,  0.46197026],
       [-0.61852221, -0.24251494]])

In [100]:
rnd.mean()

-0.6615282396212838

In [101]:
rnd.std()

1.1600120543259735

In [105]:
rnd.argmin()

3

In [104]:
rnd.argmax()

4

In [106]:
rnd.mean(axis=0)

array([-0.35693518, -0.9661213 ])

In [107]:
rnd.mean(axis=1)

array([-0.74828838, -2.2376536 ,  0.77034759, -0.43051857])

In [108]:
(rnd > 0).sum()

2

In [109]:
(rnd > 2).any()

False

In [110]:
(rnd > 0).all()

False

# Pandas